//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string BACK_1 = "back_1";
        
        public const string BACK_2 = "back_2";
        
        public const string BACK_3 = "back_3";
        
        public const string BACK_4 = "back_4";
        
        public const string BACK_5 = "back_5";
        
        public const string BACK_6 = "back_6";
        
        public const string FRONT_1 = "front_1";
        
        public const string FRONT_2 = "front_2";
        
        public const string FRONT_3 = "front_3";
        
        public const string FRONT_4 = "front_4";
        
        public const string FRONT_5 = "front_5";
        
        public const string FRONT_6 = "front_6";
        
        public const string LEFT_6 = "left_6";
        
        public const string LEFT_5 = "left_5";
        
        public const string LEFT_4 = "left_4";
        
        public const string LEFT_3 = "left_3";
        
        public const string LEFT_2 = "left_2";
        
        public const string LEFT_1 = "left_1";
        
        public const string RIGHT_6 = "right_6";
        
        public const string RIGHT_5 = "right_5";
        
        public const string RIGHT_4 = "right_4";
        
        public const string RIGHT_3 = "right_3";
        
        public const string RIGHT_2 = "right_2";
        
        public const string RIGHT_1 = "right_1";
        
        public const string F_RIGHT_6 = "f_right_6";
        
        public const string F_RIGHT_5 = "f_right_5";
        
        public const string F_RIGHT_4 = "f_right_4";
        
        public const string F_RIGHT_3 = "f_right_3";
        
        public const string F_RIGHT_2 = "f_right_2";
        
        public const string F_RIGHT_1 = "f_right_1";
        
        public const string F_LEFT_6 = "f_left_6";
        
        public const string F_LEFT_5 = "f_left_5";
        
        public const string F_LEFT_4 = "f_left_4";
        
        public const string F_LEFT_3 = "f_left_3";
        
        public const string F_LEFT_2 = "f_left_2";
        
        public const string F_LEFT_1 = "f_left_1";
        
        public const string B_LEFT_6 = "b_left_6";
        
        public const string B_LEFT_5 = "b_left_5";
        
        public const string B_LEFT_4 = "b_left_4";
        
        public const string B_LEFT_3 = "b_left_3";
        
        public const string B_LEFT_2 = "b_left_2";
        
        public const string B_LEFT_1 = "b_left_1";
        
        public const string B_RIGHT_6 = "b_right_6";
        
        public const string B_RIGHT_5 = "b_right_5";
        
        public const string B_RIGHT_4 = "b_right_4";
        
        public const string B_RIGHT_3 = "b_right_3";
        
        public const string B_RIGHT_2 = "b_right_2";
        
        public const string B_RIGHT_1 = "b_right_1";
    }
}
